### ISSUE TITLE
Additional heatframes for canLeaveCharged required

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#110]
Many heated rooms with canLeaveCharged objects need additional heatFrames to compensate for the time it takes to perform the charge when not in possession of Varia.

**Comment by fdtaillefer** [comment]
I wonder to what extent this also applies to runways in heated rooms?

**Comment by DIProgan** [comment]
It's a thing for sure.

**Comment by DIProgan** [comment]
#99 #100 #101 #104 #114
