### ISSUE TITLE
Runway clear requirement

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#113]
For a combined runway to function properly usually only one of the parts can have extra requirements to solve beforehand. However some runways are said to require nothing and still needs to be cleared up. See the two top doors in Red Kihunter Shaft. We need to have some type of indication of this such as Requires: [ "cleanup" ]

**Comment by fdtaillefer** [comment]
I think the simplest way to deal with this is to have two runways with no requirements, and for the rule to be that only the shortest runway in the destination room is usable.

Later on we could consider replacing the `null` req of the larger runway with a `canDestroyShotBlocks` which could become relevant for a beamless mode.

**Comment by DIProgan** [comment]
Considers it closed with #129
