### ISSUE TITLE
Some room traversals require a room reset

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#121]
There are some links that may not be traversable without resetting the room by exiting and re-entering, in rooms where items can make it so a plausible path could do just that. In those cases, we need an indication that the player needs to exit and re-enter (so that the logic can tell if there's something problematic about doing that)

- Early Supers, from left to right, requires a reset at the left door
- Speed booster hall, in either direction, more or less requires a reset because of the crumble blocks. Otherwise, the heat frames requirements will be way off.
- Any other places?

**Comment by DIProgan** [comment]
Good points

**Comment by fdtaillefer** [comment]
Additional point: we also need to define how this will be represented and apply it to any places that use "reset".

My suggestion is `resetRoomAtNode`, as an array of nodes IDs where the reset can be done.
So basically: `{"resetRoomAtNode": [1, 4, 5]}

**Comment by DIProgan** [comment]
Seems fine
