### ISSUE TITLE
Explicitly state if a runway is usable coming in

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#124]
Runways are meant to be added together on either side of a door, to figure out whether a `canComeInCharged` can be fulfilled that way. However, some runways are not usable when coming into the room because they requires actions that can't be done without stopping.

We've tried solutions where usable destination runways could be implicitly figured out, but it's become complicated. Instead, let's add a `usableComingIn` to the runways so it can be explicitly defined.

All runways should be continue to be considered usable going out if their reqs are fulfilled.

**Comment by DIProgan** [comment]
This can now be closed
