### ISSUE TITLE
It burns when I urinate

### ISSUE THREAD

**Issue by SmolBig** [miketrethewey/sm-json-data#14]
What do?

**Comment by miketrethewey** [comment]
Get it looked at.

**Comment by DIProgan** [comment]
Just don't show random strangers on the street

**Comment by SmolBig** [comment]
![latest](https://user-images.githubusercontent.com/36433318/56471260-52e71200-6405-11e9-8243-3b0d77ec3755.jpg)

**Comment by DIProgan** [comment]
Looks like normal to me, I think this is ready to be closed.

**Comment by SmolBig** [comment]
I tried turning it off and then turning it back on again.

**Comment by fdtaillefer** [comment]
Yeah I'm gonna call this a superpower, not an issue. Closed.
