### ISSUE TITLE
Decide and implement connection type for hallways

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#151]
Rooms that transition without doors or elevators have different connectionType in the connection files. Tourian use "Horizontal Door" while for example Crateria Tube is "Open Tube". Maridia glasstube connections are only "Horizontal Door" right now but could be something else.

**Comment by fdtaillefer** [comment]
My initial intent was that they would all be horizontal doors. The fact that there isn't actually a door would be represented by the `nodeSubType` (Tourian uses `doorway`, which I think does the job).

The rationale for that is that I'm expecting you can transition smoothly from a horizontal door to a horizontal doorway, so long as they face in opposite directions. This is already the case in vanilla, e.g. the transition between Landing Site and Crateria Tube.

**Comment by DIProgan** [comment]
I'll have a look around and change things into horizontal door with subtype doorway when appropriate.
