### ISSUE TITLE
More missing logic in PCJR

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#163]
If the speed blocks are broken in PCJR (so if node 4 is reachable), it's possible to get from 4 to 3 with just SpeedBooster and hjb. No spark needed in that case.

It's also possible to spark directly up from 5 to 3 (via the acid), but I think in that case we can leave it out because the logic will find a 5 -> 4 -> 3 path.

Shenanigans are also possible by finding a Mella that inches upwards with each dive, and making it dive until it has a suitable height for your purposes (I think that part should be behin a `canManipulateMellas` tech). You can then bring it to wherever needed and freeze it. You can get up to the left door and even the missiles that way, using only Morph and Ice. The missiles take a loooooong time though, so we might want to add a hjb rquirement to cut down on that?

**Comment by DIProgan** [comment]
Yes Hijump thnx

**Comment by fdtaillefer** [comment]
Note that the Mellas cannot be brought over to node 5 without visiting node 2. So you need either Morph or the speed blocks broken. This should probably wait until obstacles have been put in that room.

As an aside, the link between 1 and 4 is no longer one-way, so the arrow in the diagram oughta be removed.
