### ISSUE TITLE
Represent the non-respawning nature of Zebetites

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#204]
Right now each Zebetite in the Mother Brain room is represented by a link between two nodes, but nothing indicates that they need to be destroyed only once. There is also nothing to represent Zebetite skips.

The 4 Zebetites could be represented either by game flags, or with an `unlock` requirement.

Because they can be skipped, which does not flag them as destroyed, it is probably better to represent them as game flags.

**Comment by DIProgan** [comment]
Obstacles with global reach? Metroids could also be a part of this.

**Comment by fdtaillefer** [comment]
Resolved by #224
