### ISSUE TITLE
enemyDamage needs to be in one and the same format

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#239]
enemyDamage sometimes use the extra array to allow for multiple damage sources but sometimes does not. Need to decide which it will be. With the eventual removal of "cost" maybe the array is not that interesting anymore.

**Comment by fdtaillefer** [comment]
There is not one instance in the model that uses the array and actually contains damage from two different enemies.

There seems to be exactly two places that combine damage from two different enemies, and incidentally they don't use an array. They use two separate `enemyDamage` objects instead.

The documentation doesn't seem aware of the array being a thing either.

IMO, we can live without it.

**Comment by DIProgan** [comment]
Yeah two places isn't enough.
