### ISSUE TITLE
Remove metroidFrames

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#246]
The `metroidFrames` logical element is most likely redundant, and it could be a good idea to replace it with an `enemyDamage` with X hits of a drain attack from a Metroid, where one hit is one frame's worth of damage.

**Comment by fdtaillefer** [comment]
Seems to already be part of #245

**Comment by DIProgan** [comment]
Yes :D

**Comment by fdtaillefer** [comment]
#245 now merged.
