### ISSUE TITLE
Abstract Ice Beam away in helpers and techs

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#27]
"Ice" is used directly in the reqs in many places.
We should have a canFreeze helper.
We should also have a canUseFrozenEnemies to represent stepping on or wall-jumping off frozen enemies.

**Comment by fdtaillefer** [comment]
Note: We no longer want a canFreeze helper. See #38.

**Comment by fdtaillefer** [comment]
We still have references to `Ice` that need to be changed to `canUseFrozenEnemies`.
It's probably stuff that was bring worked on while this issue was being resolved?

**Comment by DIProgan** [comment]
I'm guessing "Ice" is ok if it's used as a part of a beam for increased damage rather than a technical feat?

**Comment by fdtaillefer** [comment]
Absolutely

**Comment by fdtaillefer** [comment]
Fixed again by many different commits in the junction refactor, and finalized by PR #138
