### ISSUE TITLE
Figure out how to make "view" work

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#283]
**Current situation**

Right now, at Ceiling E-Tank, we have a tentative way to describe how an item that can't be obtained can be viewed.

This data can have at least two uses:
1. Trackers using the model can indicate that an item can be viewed even if it can't be obtained.
1. A logic that doesn't require users to risk softlocks could use this information to know the player is able to check the item, and hence that this item spot is no longer a softlock risk.

**Problem**

As things stand, the `view` property is on the item node itself, which means there's no real way to know where you need to be to see it.

For example, WS Reserve can be checked from the top of the room, not by reaching the node itself.

**Suggested solution**

Flip things around. Instead of having a property on the item node to indicate it can be viewed, have a property on a node to indicates what item nodes can be viewed from there. That way, all you need is access to that node + fulfilling the view requirement, and that item is now viewable.

With that solution, `view` would be a property that takes the form of a list of `view` object. Each `view` object would indicate what item node you can view from there, along with a list of strats for viewing that item.

Here's an example of that that `view` property for the ceiling e-tank would look like. That property would be placed on node 1 (left door):

```json
"view": [
  {
    "id": 3,
    "strats": [
      {
        "name": "Base",
        "notable": false,
        "requires": [
          {"or":[
            "canShoot",
            "canUsePowerBombs"
          ]}
        ]
      }
    ]
  }
]
```

**Comment by osse101** [comment]
Firstly, `strats` would probably try to not overlap with the listed strats for collecting the item.
So I think I would rather have a `views` list following `links` using the same structure as links.  This lists strats for collecting first, then for view if collection is not possible; keeps nodes cleaner, and doesn't links to id's before they're initialized :eyes:

**Comment by fdtaillefer** [comment]
My intent is that it would be outside of `links`, yes, and basically a sibling of it. I want to re-use the `strats` scheme in there because I think it's more powerful than just `requires`. Same name and format, but different position in the schema. I want to use it to replace `requires` and `bypass` on `lock`s as well, and on `canLeaveCharged`.

Basically I'd like to allow the requirements on most anything to be a complex, togglable named strat if necessary. And it allows the much cleaner handling of obstacles that I'd like to have across the board. Then the clunky `obstacle` logical element can be taken out altogether.
