### ISSUE TITLE
Standardize door node subtype

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#29]
Some doors have subtypes based on their colors, others don't. It would be a good idea to have the subtypes everywhere.

**Comment by miketrethewey** [comment]
Brinstar: 81cb98d
Ceres: 02df756
Crateria: 8fb35b5
Lower Norfair: f28f3f2
Maridia: Outer: f27dfb4
Norfair: a000ffc
Tourian: 1c1022a
Wrecked Ship: 7f5eb0f
