### ISSUE TITLE
Cathedral Entrance strats

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#304]
Some missing strats in Cathedral Entrance:

- I think the morphed dboost off a Sova isn't there yet
- There is also a bomb boost strat (see https://youtu.be/qZk-hzQQejg)

**Comment by osse101** [comment]
This vid shows the bomb boost entry since I can't get it.  https://vimeo.com/654782047

The morphed dboost off a Sova is in now and its really a harder version of that, so don't add it.
