### ISSUE TITLE
Add single-wall break free tech

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#305]
See https://youtu.be/XSHWEKONkqM and https://youtu.be/rzFE1NafiYc.

I believe the tech requires hjb.

the East Cactus Alley strat seems to also require some kind of `singleMidAirDiagonalBombJump` which might be its own tech too.

Note: There is also a mid-air SpringBall in East Cactus Alley right-to-left: https://youtu.be/BHiXx9pLfPc

**Comment by osse101** [comment]
I believe this is jumping in-room from the halfie climb room mid door to break the waterline with walljumps.  And the other vid is same but on the other side of the door in east cac alley.

Imo do not add.  Its a one wall underwater walljump combined with break free timing.
