### ISSUE TITLE
Mt. Everest: Crazy crab climb to top door

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#306]
So there's a crab climb to the top door. See https://youtu.be/Z9zMjNvaZPo

This video also shows that the crab climb to the top right door is doable without supers, we could consider a separate superless crab climb strat.

Alongside this comes an observation that many of the crab climb strats should start and 2 and go to their proper destination, because access to 2 is needed to get the a lot of crabs to begin with.

There is also a small crab climb that can be done when entering at node 3, by quickly shooting a super then freezing the crab. This should require a reset at node 3 with `mustStayPut`.

**Comment by kjbranch** [comment]
I'll leave this one open for now, but I would be fine if someone else wanted to close it.
