### ISSUE TITLE
Add lava dive strats

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#310]
See https://youtu.be/Il2eJdKMBZ0
Notably, there is a hj + varia strat that needs no e-tank. decide what is detailed there that we should add.

**Comment by osse101** [comment]
This video was about the max% lava dive.  Jump off a namhie head then do a frame precise wiggle to remove walljump state.  followed by a right side bubble mountain style jump with no time to position.  Its only for conserving health and very unreliable so shouldn't be added.

There is also a strat in hjless suitless to avoid the nahime hit by kagoing into the bottom left head for iframes.  I wouldn't add that either for the same reason.

**Comment by kjbranch** [comment]
Should strats be added that require Gravity but not canLavaGravityJump?

**Comment by osse101** [comment]
SpaceJump and Lava Spark are in already.
IBJ I would add if I could do it acceptably well.
And I don't know that I've looked at any springball strats with gravity.  But there are more springball no gravity strats that could be added.  Or maybe its just double springball jump, springwall would be beat by normal lava dive.
