### ISSUE TITLE
New strat - Colosseum ledge grab

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#351]
See https://clips.twitch.tv/CaringAcceptableFoxWoofer

It seems to require HiJump, the upwards equivalent of a crumble quick drop (which seems not to be a tech right now and maybe ought to be), and an adjacent dry runway of at least 2 tiles.

There may be an equivalent with just speed and no HiJump, but it would require more tiles.

**Comment by kjbranch** [comment]
Added in #578
