### ISSUE TITLE
Missing: CF clip in Botwoon Hallway

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#355]
Saw a runner use crystal flash clip in a race to get through the Botwoon Hallway so it seems like something to be included.

**Comment by fdtaillefer** [comment]
CF clip is someone we haven't gotten around to yet. It's usable in Pants Room too.

**Comment by DIProgan** [comment]
There's also the ability to reach the missiles in Golden Torizo room.

**Comment by fdtaillefer** [comment]
I'll stick to RTA viable stuff, thanks.

**Comment by osse101** [comment]
Most people do these two CF clips with gravity and morph bombs.  
But its also possible to do them with just morph and ammo.  Should probably add both item sets.

**Comment by kjbranch** [comment]
I recently implemented this in Spring Ball Maze and Mission Impossible. Those can be done on the ground and are easy to do.

Other rooms that might be possible for CF clip:
- Etecoon E-Tank
- PCJR (crumble block below the Indiana Jones Missiles)
- Acid Statue Room
- Mickey Mouse Room (possibly easier than the ice clip)
- Bowling Alley (top right to get to the very top door)
- West Ocean (through the crumble block near the door to the Moat)

Possibly OOB stuff which shouldn't be added but might be fun to see if it's possible:
- Homing Geemer Room
- East Pants Room

**Comment by osse101** [comment]
CF clips only work on crumbles that do not respawn.  TAS can do it in GT room but with TAS magic.  Maybe a low to the ground crumble you could make it through.  I was trying it on the solid block in acid statue room and couldn't stay above it.  

Botwoon hallway and East pants room(lower) for sure should have it.  And players have gotten good enough now that the suitless botwoon hallway clip should be in.

**Comment by osse101** [comment]
Revised List:
Botwoon hallway (gravity+bombs) and suitless
East Pants Room (grav+bombs) and (suitless with room items)

Acid statue room with grapple
Mickey Mouse with grapple (You need to be on the leftmost crumble and fall on the solid block)
Above WS reserve with grapple

The technique is to select grapple as your health refills then hold down and mash shoot.  Earlier you shoot the better.  It puts you on top of your current block.

Homing geemer presumably works but is oob.
