### ISSUE TITLE
Reverse Crateria Supers

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#364]
Reverse Crateria Supers is quite possible if coming in charged (with 180 frames remaining, i.e. coming in blue), with Space Jump and a Mockball (so a Speedball in this case).
Probably not possible to grab the item at the same time though. Might need to rework the nodes for this?

**Comment by osse101** [comment]
Use case for pick up item->xray to turn around and keep blue->fall through speed blocks

**Comment by osse101** [comment]
I'd rather require you do the speedball on a separate visit than add springball into xray turnarounds as a requirement.

But you can XMode in the spike pit to build a blue suit.
