### ISSUE TITLE
Strat: Remorph Zeb Skip

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#371]
There is a strat to do a morph zeb skip without using springball or bombs, but unmorphing and remorphing.
See https://www.youtube.com/watch?v=gAWHhbkeuY4

Add this?

**Comment by osse101** [comment]
The timing is a bit easier if you know how to do it, but the spinjump zeb skip is otherwise equal or better.  Its mainly used to avoid pausing to turn off screw attack.

**Comment by fdtaillefer** [comment]
Since there was already a strat and tech for Morph Zeb Skip (using a bomb or spring ball), I just replaced that one with remorph since it's pretty much the same setup but with less item requirements.
