### ISSUE TITLE
Strat: Mama Turtle bomb boost

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#431]
Walljumping and bouncing off of a power bomb lets you touch the Etank item.  Morph bombs also work. 

https://youtu.be/Epd_aaRgTvg

**Comment by kjbranch** [comment]
Osse: Do any of your new bomb tech make this easy to implement?

**Comment by osse101** [comment]
canWallJumpBombBoost is what I called this one.  
The moat issue also uses some of my bomb techs
