### ISSUE TITLE
Fix West Sand Hall logic

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#455]
Currently, the link from 1 to 3 in West Sand Hall can be traversed suitless with just high jump boots.

This seems incorrect. The options with hjb should be:
* Jumping with enough momentum (requires an adjacent runway that is dry). Confirm whether it's doable bootless (that jump works but you're essentially getting stuck in sand after that anyway). In any case, consider this out of scope until #456.
* hjb + a SpringBall Jump
* A shinespark across the room also works both ways

There is also an additional strat, covered by https://github.com/miketrethewey/sm-json-data/issues/314

**Comment by blkerby** [comment]
Yeah I was wondering if we may want to annotate each runway as dry or not, and then add an adjacentDryRunway requirement (or maybe an annotation to the existing adjacentRunway requirement)? It seems that cross-room jumps like this are turning out to be a fairly commonly applicable strat in Map Rando; I think there's many places they need to be added once we have a way to express them.

**Comment by fdtaillefer** [comment]
I've been thinking about that.

Initially, it seemed like it might not be necessary because all "wet" runways require Gravity to be usable, and those cross-room jumps are usually made redundant by having Gravity in the submerged room.

However, that is quite the assumption. It could be possible that there are edge cases where that won't hold true. It also doesn't seem like a very expensive solution. Just add a boolean to the runways, and add an optional one to `adjacentRunway`, and it's a very easy to check make by logic.

I'll create an issue so the idea doesn't get lost.

**Comment by blkerby** [comment]
Makes sense. Was chatting with kyleb and we're also wondering if there might be a case where it could be useful to get some speed using a submerged runway with Gravity and then disable Gravity shortly before or after the room transition for the jump in the next room. Not sure if that would be useful or how it would be expressed in the logic but just wanted to throw it out there.
