### ISSUE TITLE
Make widescale use of `canJumpIntoIBJ`

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#460]
Since https://github.com/miketrethewey/sm-json-data/pull/454 added `canJumpIntoIBJ` tech, there are a few places where it should be used instead of `canIBJ`. Go through the model to find and replace those.

It should be done at least:
- In Post Croc Jump Room (IBJ from a Kamer)
- Crocomire Escape (IBJ from a platform made of bomb blocks)
- Any other place with heat frames (in that case, an alternative slower strat could be added)

**Comment by kjbranch** [comment]
This is now used in these two locations as well as:
- Plasma Room: Need to jump to start it to avoid being shot by a pink space pirate
- Mama Turtle: To start an IBJ from her shell before she drops

It still needs to be added in hot rooms.

**Comment by miketrethewey** [comment]
Do you have a list of any specific locations available?
Task lists are sexy.

**Comment by kjbranch** [comment]
An enumerated list would be long, but it is all heated rooms that have a wall jump in them that can be replaced with an IBJ, or any room that has an IBJ in general that isn't too long to require heat proof.

**Comment by kjbranch** [comment]
The remaining tasks from this issue are in #540
