### ISSUE TITLE
Add more explicit support for strats that rely on vertical cross-room physics changes

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#470]
Broken off from #456 because vertical momentum is its own problem

Some things in submerged rooms can be done by coming in with enough upwards momentum from a bottom vertical door. However, the amount of momentum Samus has notably has nothing to do with runways and cannot be calculated simply in a number of running tiles. It instead depends on many factors:

* Whether Samus has hjb
* The vertical distance from the door
* The kind of jump Samus is making:
 * From a platform, which also has the following factors:
  * Whether Samus has Speed Booster (which also brings in the amount of running speed and makes the momentum super volatile)
 * From a walljump
 * From a Space Jump
 * 
See https://wiki.supermetroid.run/Vertical_Speed

We need an elegant way to represent the possibilities in the adjacent room, and an elegant logical element in-room to express the amount of momentum needed. 

We want to avoid tying the model's language to in-game physics rules. It's much easier if we can stick to easily-measurable things like numbers of tiles. The problem is that running jumps involving Speed Booster have very variable initial jump heights, so a bunch of different combinations could work and it's hard not to rely on a formula.

**Comment by kjbranch** [comment]
Added in #807
