### ISSUE TITLE
Add Samus-eater shine-charge strats in Hellway

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#488]
In Hellway, it is possible to use a Samus eater to charge a shinespark and then spark (or leave charged?) through either the left or right door.

**Comment by DIProgan** [comment]
Should be possible in Alpha Power Bomb room as well. canEaterSpark

**Comment by osse101** [comment]
Fun fact, yapping maws don't hold you long enough to charge a full spark.

This really resembles X-mode so maybe there's more to break here.  You can also spinjump out after gaining blue but I bumped into platforms before turning it into something useful.  The spikesuit potential is there though.

**Comment by kjbranch** [comment]
#499 should have resolved this.
