### ISSUE TITLE
Add Flatley jump strat in Fish Tank

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#489]
It's possible to get into the top-left door of Fish Tank without freezing the fish, by using a Flatley jump with Hi-Jump. 

https://clips.twitch.tv/ArborealWonderfulNostrilYee-SWBAIo-A3kgvErDT

Also check if a spring ball jump could possibly work here without Hi-Jump or freezing the fish?

**Comment by osse101** [comment]
There were more missing in Fish tank room so I've written out all the node traversal techs I could think of.
(y) for already implemented
(x) for do not add
(fix) means there are unnecessary requirements in the code
(?) means I'd have to try in SMILE to confirm

```
1-4
grav + ibj (y)

1-5
grav + walljump/space/hjb+speed/ibj
hjb + spring + ice (y)
hjb + 2spring
grav jump through door with some extra requirements(?)
enter with stored spark

4-5
ice+wave+plasma
ice+plasma+charge
ice+wave+spazer+charge
reset fall speed (unmorph on room entry)
enter with spark stored

5-4
grav + ice/space/walljump/ (double hbj/dhbj/ fall and ibj)
grav + aim down(hitbox manip)
ice + hjb (y)
hjb + flatley
hjb + wall hug turnaround
ice + springball jump (y)
flatley+springball jump

2-6
grav (y)
hjb (y)
springball (y)

2-5
enter with spark + enter with momentum (?)

5-2
go through 6

6-2
any (y)

6-5
grav (y)
hjb (y)
springball (y)

5-6
any (y)

6-7
any (fix)

7-6
any (y)

7-3
grav (y)
hjb (y)
springball (y)
Underwaterwalljump (x)

3-7
any (y)

4-1
any (y)

5-1
any (y)
```

**Comment by osse101** [comment]
To clarify `reset fall speed (unmorph on room entry)`: the vertical momentum reset has to happen before entering the room, pretty much in the door shell or later.  Amd it uses water physics so you can't have gravity equipped.

And I forgot there is a dboost you can do with gravity off the fish to go 4->5

**Comment by kjbranch** [comment]
Osse, are all of these completed now?

**Comment by osse101** [comment]
Yes.
