### ISSUE TITLE
Add some bomb jump strats to the bottom of Red tower

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#491]
Three possible strats:
* A double hbj: https://clips.twitch.tv/TentativeWealthySrirachaHoneyBadger-9cKymgLDerbVXGSd
* Staggered bomb jumps from the bottom, alternating regular IBJ and double IBJ to avoid the rippers
* Infinite diagonal bomb jumps

**Comment by osse101** [comment]
There are some strats dealing with no walljumps to add as well

```
7->6
Speed+HJB (no walljump)
ice + springballjump (no walljump)
ice + ibj
walljump+ double air horizontal bombjump
walljump + midair infinite diagonal bombjump

8->6
Staggered ladder bomb jumps (no ripper kill)
Sinking IBJ + off temp IBJ ( I wouldnt add this)
```

**Comment by kjbranch** [comment]
#496 should have fixed everything in here
