### ISSUE TITLE
Add details to runways and other charge/spark representations

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#55]
Whether they are represented by an actual runway or a number of tiles required to charge a spark, runways could use more contextual data to help determine what's possible.
Things that may be useful:

- Number of diagonal tiles on the runway (if more than 0). These apparently add a little bit of extra leeway.
**Diagonal tiles don't work the same way going upwards and downwards, so we can't do this unless we figure out a good representation**
- ~~Number of open ends on the runway (if more than 0). An open-ended edge tile leaves more room to work with than an edge tile that is against a wall.~~
**This has been done**
- Whether the runway starts on a downward slope, in the direction it's likely to be used. This is relevant because stuttering doesn't work then (Example: charging a spark to the right at the bottom of maridia main street).
**This has the same issue as diagonal tiles**
- ~~Whether a spark is actually needed. We could have it as a separate req, but that would be more cumbersome. We can most certainly default that value to true and only specify it when you don't need a spark.~~
**This has been done with a `shinesparkFrames` property. 0 means no spark**
- ~~When a spark is needed (whether it be in a canLeaveCharged at 0 frames, a canComeInCharged, or a canShineCharge), the frame duration of the shinespark should also be included. Sparking is 1 damage per frame.~~
**This has been done**

**Note:** This applies to runways, but also to canLeaveCharged and canShineCharge objects.

**Comment by miketrethewey** [comment]
#54 does some runway work.
