### ISSUE TITLE
Add a lock property to doors

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#57]
Some doors are only locked when some conditions are met, and then unlocked when further conditions are met.

The model currently represents those strictly as unlock requirements, where the requirements to unlock need to be met OR the requirements to lock need to NOT be met.

It might be an improvement to have separate requirements to lock and unlock the door so the model can adequately represent the situation. The lock property should be optional, and all doors with no lock property should simply be assumed to always require their unlock property to be fulfilled.

Rooms that have locking requirements that I can think of:
- Bomb Torizo Room. Its door locks only if you have Morph Bombs.
- Attic. Its bottom door locks only if you have defeated Phantoon.
- Bowling Alley: The Mid-left door locks only if you have defeated Phantoon.

Many other doors are also locked during the escape sequence and cannot be unlocked from that point on, we might be able to represent those as well. Bomb Torizo Room might be more tricky since it has two separate sets of locking and unlocking requirements (locks with bomb, unlocks by killing Bomb Torizo, locks again with escape, and unlocks by saving the animals). ~~However, we probably don't need to model that second lock/unlock.~~ We will model both locks. Anyway, it turns out all colored doors that get locked during the escape also need two `lock`s.

While working on this, also add a `BeatSuperMetroid` flag that is attained from an additional node next to the ship, and the `SaveAnimals` flag that can be attained in Bomb Torizo Room during escape.

**Comment by DIProgan** [comment]
```json
"lock": [
            {"and": [
              "Bombs",
              {"not": [
                "DefeatBombTorizo"                  
              ]}
            ]},
            {"and": [
              "ZebesSetAblaze",
              {"not": [
                "SavedTheAnimals"                  
              ]}
            ]}
          ],
```

**Comment by fdtaillefer** [comment]
That doesn't solve the issue that `unlock` is once and for all, I don't think.

**Comment by fdtaillefer** [comment]
The format we settled on is:
```json
  "locks": [
    {
      "lock": [
        "Bombs"
      ],
      "unlock": [
        "DefeatBombTorizo"
      ]
    },
    {
      "lock": [
        "zebesSetAblaze"
      ],
      "unlock": [
        "animalsSaved"
      ]
    }
  ],
```
This way, a node can have several independant lock conditions, each with an associated unlock condition.

**Comment by fdtaillefer** [comment]
This has been finalized with #205.
