### ISSUE TITLE
Add Grapple considerations to enemy definitions

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#58]
Our enemies files have a lot of data about enemies, but there is no information about what happens when Samus uses Grapple Beam on enemies.

There are at least 3 possible results:
- Nothing happens
- The enemy is killed
- The Grapple latches onto the enemy as if it were a Grapple block

It would be worthwhile to decide how to represent this, and then add the data in the enemy files.

**Comment by miketrethewey** [comment]
Some work done in 28c1855 .

**Comment by miketrethewey** [comment]
I think we're done here.
