### ISSUE TITLE
Further define unlock condition "Kill All Enemies"

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#68]
There are two things that need to be changed for grey doors with the unlock condition "Kill All Enemies":

1. ~~The requirement is actually killing a specific number of enemies. In some rooms, that number is smaller than the number of enemies in the room.~~ **All rooms where this happens can be dealt with by overriding (see point 3)**
1. ~~It would be very nice if we could just place the enemies in the room and have the logic infer the requirements to kill them, based on their immunities~~ **Enemy placement has been completed**
1. In some cases (especially for heat frames), we may want to be able to override this. This can be done by simply not have the "Kill All Enemies" condition at all. The packs of enemies to kill can be represented by obstacles when necessary.
1. ~~In all cases, overridden or not, the system needs a way to understand that the requirements are caused by the presence of enemies.~~ **This can be implied by "Kill All Enemies", and in the case of an override it can be implied by the presence of an `enemies`-type obstacle.**

**Comment by fdtaillefer** [comment]
Rooms that need to be explicitly overriden, mainly due to heat frames or other requirements to take damage:
- ~~Metal Pirates Room~~ **Already done**
- ~~Mickey Mouse Room~~ **Already done**
- ~~Morph Ball Room: Kind of done but needs to be elaborated (e.g. If you can go hide behind the bomb passage, you can kill them with power beam pretty safely)
- Pink Brinstar Power Bomb Room
- Pink Brinstar Hopper Room
- Beta Power Bomb Room

**Comment by DIProgan** [comment]
Seems Metal Pirates is not quite done. At least it still got the Kill all enemies req and a fixme.
