### ISSUE TITLE
Lower Norfair Spring Ball Maze heat frames

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#707]
It is possible to grab the item with get back out with no tanks, using only Missiles.

Clip: https://clips.twitch.tv/DistinctSarcasticKeyboardGrammarKing-sV3vOriisowG6SIZ

It helps to have run speed from the previous room and get an energy drop from the Alcoon but these are not required.

The logic currently implies this would take 460 heat frames (or 425 plus an Alcoon hit).

**Comment by osse101** [comment]
This is still an issue.
-Entering the room with run speed
-Killing the Alcoon from the left
-Getting the health drop
are all not modelled.  
You can just barely make it to the missile and back without any of those but not with expected movement.

Entering with run speed is fine to add.
Not killing the alcoon as it is now may not even be correct.  You can run under it and kill it later but that adds dodge time later.  Whereas if you CF clip from the right, you wouldn't have to kill it at all either.
