### ISSUE TITLE
Add strat for 5-missile Croc

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#710]
A 5-missile Croc fight seems to be viable. Oatsngoats did it at least a couple times successfully in a recent seed: https://www.twitch.tv/videos/1794797322?t=4h24m28s

Let's add a notable strat for this one. The trick seems to be maintaining full energy so you get lots of missile drops, and then firing multiple missiles while postponing collecting missile drops until your missile count is low enough to not be saturated by them; when the drops are gone, fire one missile at a time.

**Comment by osse101** [comment]
Knowing when your drops are about to despawn is another factor.  And being able to damage croc while it is shooting orbs, without getting hit.
But mostly the never get hit part.
`Croc proficiency 2.0`

**Comment by osse101** [comment]
Croc could actually use a `canCrocFarm` sort of tech.  Missile scaling is kinda noteworthy too.
Extreme/Insane 5cap+1 to start
Expert 10cap
VH 15cap -canCrocFarm assumed here-
Hard 30cost
Int 40cost
Beg 50cost

**Comment by osse101** [comment]
added in #914
