### ISSUE TITLE
Add canIceMoonfall tech and strats

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#712]
Using two frozen enemies it is possible to gain moonfall speed in place.

Examples:
- Clipping down through Speed blocks in Dachora Room: https://vimeo.com/815495126
- Downward G-mode setup in Parlor: https://vimeo.com/815864664

Let's create a new tech ("canIceMoonfall") for this and add these strats and others like them.

**Comment by osse101** [comment]
Basically all of these are going to need a room specific setup.  With these examples, there is a piexl perfect freeze on the flyer, and for the Parlor clip it is leaving the moonfall in a small frame window.
Refreezing while moonfalling can be called impractical.
