### ISSUE TITLE
Support water shinecharging strats

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#774]
We need some way to represent cross-room water shinecharging. Here are some initial thoughts on how this could be done:

We could have a tech "canWaterShinecharge" for basic cases like Aqueduct where you don't need to stutter coming into the room. And then maybe "canWaterShortCharge" for the stutter version. The difficulty of getting the stutter depends on how many runway tiles are available in the neighboring air room. So we could have a numeric "Water short charge setup tiles" setting in the randomizer, similar to the existing "Shinespark tiles" in Map Rando for regular short charges? I guess there's another dimension of difficulty based on how many tiles are available in the water room, which determines how accurate the timing of the stutter has to be in the setup. I don't have a good understanding of if these can interact; i.e., does having a longer runway in the air room make it possible to get a shinecharge in a shorter distance in the water room, or does it just affect the difficulty of getting it?

Then there's the question of how to express requirements. I can think of a few options:

1) Use "adjacentRunway" in the water room to express the need for a neighboring runway with air physics (or I guess having Gravity can work too, with a well-timed pause to unequip it?). The problem is the number of tiles required may depend on difficulty settings, which this can't express. One solution is we could allow a special string to be used in place of a constant integer in the "usedTiles", e.g.

```
{"adjacentRunway": {
  "fromNode": 1,
  "usedTiles": "waterShortChargeSetupTiles"
}}
```

The randomizer could then resolve this string to an integer based on the difficulty settings.

2) Use the existing "canComeInCharged" requirement, but change the rules for how the runways combine when dealing with a mix of air and water physics. In theory this could allow for simpler requirements where in a strat a single "canComeInCharged" could handle multiple possibilities (in-room charge, other-room charge, cross-room normal charge, cross-room air-to-water charge). This would require reworking how runways work because right now in water rooms the runways have a "Gravity" requirement which would either have to be pulled out or overridden. My main concern though is that "canComeInCharged" is already very complex to interpret because of all the different possibilities it can represent. If anything, rather than cramming more possibilities into "canComeInCharged", at some point I would lean more toward trying to split it apart into separate, simpler requirements, e.g., using different requirements for running into the room vs. getting the charge in the other room and carrying it in vs. sparking through the door, since these are all fairly different things. The readability of the logic & spoiler log could be improved by having these split into separate strats, but I guess this has to be balanced against the need to create more strats and the increased risk of missing strats that are possible.

3) Create a new requirement type, e.g. "comeInWithWaterShortChargeSetup" or something along those lines. I think making a new requirement type can make sense if it turns out that we need to do a calculation combining the two runways and/or difficulty settings in some new complicated way. But if "adjacentRunway" is expressive enough (with the addition of a constant to use in "usedTiles") then that would seem preferable.

4) Instead of having a continuous new difficulty setting, we could just have a few tech to represent abilities to get the shortcharge setup in the air room with a few fixed amounts of runway. For example, we could have "canWaterShortCharge" represent being able to do it with 5 tiles and "canWaterVeryShortCharge" represent being able to do it with 0.5 tiles (or whatever the minimum reasonable/possible amount is). Then strats in the water room would have requirements that look like

```
{"or": [
  {"and": [
    "canWaterShortCharge",
    {"adjacentRunway": {
       "fromNode": 1,
       "usedTiles": 5
     }}
  ]},
  {"and": [
    "canWaterVeryShortCharge",
    {"adjacentRunway": {
       "fromNode": 1,
       "usedTiles": 0.5
     }}
  ]},  
]}
```

This has the advantage of not requiring any new support in the schema. The drawback is that strat requirements are more verbose, and if we ever want to refine the tech to add or change the number of tiles, then it would require changing it across all the strats (although the number of strats using this is probably not huge since it's only applicable in water rooms).

**Comment by kjbranch** [comment]
Here are rooms in which there is a likely useful runway with 12+ tiles:
- Oasis
- Crab Shaft
- Aqueduct
- Botwoon E-Tank
- Halfie Climb
- Precious Room
- Plasma Spark
- Main Street
- Fish Tank
- Crab Tunnel
- Mama Turtle

These rooms have a runway, but the runway is likely only useful when leaving or crossing through the room. Something we will likely not be able to represent at first:
- Oasis (Cross the room)
- Main Street (Top right)

**Comment by osse101** [comment]
Runway math would look something like this
Animations underwater take twice as long as dry
Run speed stops increasing after a certain value in dash state and underwater.  I'm seeing it stop at different speed values so I don't know how it decides this.
Run speed if higher than the value will stay the same when entering water.
You will reach speed echoes before hitting max run speed while dry.
Shortcharging in air is still functional but in water all you can do is hold forward.

Here's some data points.  Not super correct but within a tile.
Just running gravity  3+30  vs no gravity  3+44
Stutter 1       gravity  3+19  vs no gravity  3+31
Stutter 1       gravity 13+11 vs no gravity 13+20
Stutter 2       gravity  8+12  vs no gravity  8+20
Stutter 3       gravity 13+9   vs no gravity 13+16
Stutter 3       gravity 13+6   vs no gravity 13+10

**Comment by osse101** [comment]
Sponge bath can be done in room with a water stutter if walljumps were disabled.  Or across rooms with a longer runup.

**Comment by kjbranch** [comment]
True, that could be used for leaving the room. I would assume the in-room jump would put it out of logic for simply crossing the room tho.

**Comment by blkerby** [comment]
This was implemented (in a simpler way than originally proposed) in #781 and #787.
