### ISSUE TITLE
Add Three Musketeers and Red Kihunters strats

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#810]
In two rooms:
- Three Musketeers could have a strat for morphing under the Kihunters.
- In Red Kihunter Shaft currently all the strats going to the top require killing the enemies or tanking 2 hits. I think alternatives should be possible with plasma hitbox, morphing under, and/or RNG manipulation to go around them but I'm not familiar with the exact strats.

**Comment by osse101** [comment]
shaft:
Heat/Proof run through can be merged.
Its weird that canHitbox doesn't have a strat here.
A strat for kill with supers can be added.
Any% can manipulate the kihunters coming from the bottom door, not 100% reliable but its pretty good.  You would need bombs and hijump, surely.  And I don't know if low% has a manip or not, but they've tried to find one I'd imagine.

I asked in league discord about a manip from the save room and was shown https://streamable.com/ocji8u 
It works really well.  Having morph makes a big difference; there was another clip for morphless that I couldn't get to work quite as well.

Musketeers:
There is a manip in any% and probably low% if you skip the item, but it does take a lot of practice.
The problem with these ki's is when they are close to the hole up to their level, it is hard to avoid them no matter what you do, other than the first.  Rolling under or jumping under a swoop takes pretty much the same understanding of their patterns, but if you can do both you'll have options.  Morph helps right near the ledge where you can decide to attempt a walljump+morph overhead, or land precisely on the corner and morph under.

Going down, you can avoid them all with nothing.
Coming up, dodging one is reasonable.  Dodging two is hard, but if you move fast you can iframe through the top one sometimes.

**Comment by osse101** [comment]
fixed in #896 and #890
