### ISSUE TITLE
Rework ceiling clip tech

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#817]
We need some way to take into account that (at least in most situations) HiJump helps with ice clips as much as XRay+Morph. We could put the HiJump logic into the (already complicated) requirements for the tech canNonTrivialIceClip, or we could pull it out of the tech and put it into individual strats. My initial thinking is the second option seems better: though more verbose, it's more flexible, and being more explicit can make it easier for someone to understand when reading the logic.

Also, maybe it's not necessary to have separate ice/snail clip tech: e.g. instead of canNonTrivialIceClip and canPixelPerfectIceClip we could have canNonTrivialCeilingClip and canPixelPerfectCeilingClip, and we can get rid of canSnailClip? There's also canMochtroidIceClip, which we could also get rid of (becoming covered by canCeilingClip), ending up with a hierarchy like this:

  canCeilingClip < canNonTrivialCeilingClip < canPixelPerfectCeilingClip

Then we could also get rid of all the enemy-specific ice clipping tech ("canBeetomIceClip", etc.); particularly tricky cases could be reflected as notable strats.

**Comment by osse101** [comment]
snailClip is pretty much exactly the same as wallcrawlerIceClip.  One difference is that people are used to having a visual cue for the snail clip placement and haven't had a reason to learn cues on wallcrawlerClips.  Another difference is you can buffer XRay to stop a snail to better position it, but using XRay will not allow you to use ice right after.

MochtroidClip would fall under notable ceiling clip in that case.  The inputs are only trivial after you know what they are.  You probably have to be a little fast with button presses too.

PixelPerfectIceClip is essentially an extension of NonTrivialIceClip and for those I've been putting the helpful items into the strats themselves.  But you could do it with a helper.  HiJump vs Morph is a little different in that morph lets you position on top of the enemy easier.  Maybe that is a bigger problem for certain clips.  They help a similar amount, but I'd rather have morph+xray.

Enemy specific clip techs aren't that helpful.  I think it was written that way for enemizer.

**Comment by osse101** [comment]
I am considering renaming `canSnailClimb` to `canManipulateSnails` then replacing `canSnailClip` with `canManipulateSnails` + `canNonTrivialCeilingClip`.

**Comment by osse101** [comment]
I was aware no HJB crouch jump had a two pixel range, and that HJB helped some, but the rest is new to me.

For wall crawlers and beetoms I look at the walltiles.  It doesn't help that much, and is tile set/palette dependent, but its something.

**Comment by kjbranch** [comment]
I did the same analysis for snail clip and found that HJB had no benefit. So I bet it was based on subpixels and HJB helps for less than 1 pixel:

crouch jump, no HJB: 35-37 px below (3 pixel range)
crouch jump, HJB: 35-37 (3)

In addition, x-ray + morph adds these:
no HJB: 23-29 (7)
HJB: 23-29 (7)
HJB no gravity: 23-26 (4) [only through the first barrier]
no HJB no gravity: Didn't test

Takeaway:
- Snail clip should probably be a more similar difficulty to these ice clips
- HJB helps even less than originally thought, so it's likely not worth modeling

**Comment by osse101** [comment]
That's a surprise
