### ISSUE TITLE
Rework LN Spring Ball Maze Room

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#822]
Currently there are no requirements for 3 -> 1 (bottom right door to top left door) other than heat frames, which is incorrectly implicitly assuming canWalljump. Aside from a wall jump, there are many ways to get up, including HiJump, Space Jump, spring ball jump, tricky dash jump, IBJ, which should all be modeled.

In general the heat frames in this room are higher than required and should be timed more accurately (see #707). 

Dealing with the Alcoons at the bottom should also be modeled (e.g., either wait and jump over them, taking extra heat frames; or kill the first in one shot with a Missile, Super, Wave+Plasma, or Screw Attack)

It could help to add a couple junctions, one just to the left of the bottom Alcoons, and one on the platform just above. Direct strats should also be included going from that higher junction to the item; currently, you would have to go to the left door first, which requires more heat frames than necessary.

**Comment by osse101** [comment]
fixed in #893
