### ISSUE TITLE
Add right-side X-ray climbs with suitless water setup

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#863]
Instructions from bobbob:

```getting stuck suitless right side is the "same" frame boundaries as cwj over the moat, so it is "learnable". the normalized way is:
(1) full height spin jump in door while facing right (as normal);
(2) press right to trigger door transition at the correct height;
(3) after door transition, press down on the correct frame (while still holding right), to grab the closing door. the correct frame is usually the second frame that you have control of samus after the transition. if you are just trying to get it, you can mash down (while holding right); it should be better to try to learn the timing, though.
for unnormalized, you may find it easier to just do a low height jump in the door. it could potentially improve frame boundaries.
```

I tested this for a water-to-water transition (Glass Tunnel Save Room into Glass Tunnel) and was able to get stuck standing in the door. We should check to make sure it also works for water-to-air and then add tech and strats for this. I don't have a good feel yet for how its difficulty compares to the regular setup for right-side climbs (i.e. using dash and aiming down through the transition).

**Comment by osse101** [comment]
I was able to get it in water-to-air.  It was about the same as water to water.
Easy insane tech placement.  Regular setup has a 2 frame window, I once heard.  And this is double frame perfect with something about subpixels affecting your frame window?
