### ISSUE TITLE
Add ice strats in Spiky Acid Snakes Tunnel

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#864]
It is possible to freeze the snakes and use them as platforms, to reduce the damage taken. Haven't tried this yet, but looks like Morph also helps a lot here.

Example clip by sapphron (could probably be optimized a little further):
https://clips.twitch.tv/BelovedCloudyOkapiCoolStoryBro-hK_KRLxeuT3jhL2O

**Comment by blkerby** [comment]
Video without Varia, by insomniaspeed:

https://discord.com/channels/1053421401354285129/1053436236628496454/1120369075583975526

**Comment by osse101** [comment]
Added in #903
