### ISSUE TITLE
Add canSpeedKeepChain strats for Main Street item

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#897]
Video by insomniaspeed (in Map Rando discord): https://discord.com/channels/1053421401354285129/1053436236628496454/1126913011697864806

With certain items, this should also be possible from the lower doors on the right side of the room (though with limited applicability since shinesparking is usually a better option).

**Comment by osse101** [comment]
Added in #901 

And there were some fun and unfun ways to bring one up from below.  A gravity jump is a not too hard way to do it.  Mixing Ice/HiJump/Springball jumps when suitless is a lot of complexity.
