### ISSUE TITLE
Baby Metroid Skip Methods

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#908]
`canBabyMetroidAvoid`

We have HiJump+Speed+Morph+Wave as the baseline skip.
And another version without wave.

Stashio skip goes the other direction and doesn't need Morph.  I'm not sure which beams it needs.
HiJump+Morph+Wave is not much different from the versions with speed.  Which means it can be done without Wave.
And the skip can be done without HiJump or Speed, but I'm not sure what else is needed, if anything.

Powerbombs as a replacement for wave doesn't seem meaningfully easier than shooting the wall out bit by bit.

**Comment by kjbranch** [comment]
The current strats in logic don't require speed, even though the tech itself says that they should. 

It sounds like the tech could remain, and be used for all of these, and then most of them will be notable.

We are a long way off this, but I recently saw someone do the baby skip with a flash suit.

**Comment by osse101** [comment]
I feel like most people didn't try to learn it without speed before this past year so I'm kinda surpried it's not a requirement.  It does make sense to me to have a tech for this group of notables, describing `Classic Baby Skip`.

Flash suit Baby Skip is ancient tech.  You would get a slope spark in terminator and carry it through half of Tourian to use here.
Some similar evenetual ideas are using the Baby grab to get a blue suit with either a CF or shinespark with the right timing.
