### ISSUE TITLE
Simplify how obstacles work

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#909]
Currently the semantics for strat requirements involving obstacles are fairly complicated. A strat has a "requires" property with the unconditional requirements, and then it has conditional requirements under "obstacles" which are only required if the corresponding obstacles are not yet cleared; each obstacle can also have a list of "additionalObstacles" which indicate that the given obstacles are cleared as a side effect of performing the strat (but only if the corresponding obstacle is not already cleared).

The result is that the effective requirements for doing a strat can vary a lot, depending on the state of the obstacles. This causes a few problems:
1) In Map Rando, it makes it difficult for players to interpret the logic pages, as the meaning of "Obstacle" requirements vs normal requirements is not intuitive. 
2) In Map Rando, it causes a problem in how strats are assigned to a difficulty tier in the logic pages: hard strats can end up being assigned to a low difficulty tier because their hard requirements are only conditional on an obstacle not being cleared (and the difficulty tier for the logic pages is based on the best-case scenario, where the obstacle would already be cleared).
3) Similarly, in Map Rando, even on Basic difficulty settings the spoiler route can end up saying to use complicated strats like a "Speed Keep" which can be in logic because the obstacle (block) was already cleared by an earlier strat, and the "canSpeedKeep" tech requirement was in an "obstacle" which isn't applicable in that case.
4) Obstacle requirements expressed using an "obstacles" property are not composable; e.g. you can't put them in an "or" to combine them with other requirements.

As I see it, the root of the problem is that the "obstacles" property is trying to do too many things, both indicating strat requirements and also indicating side effects of doing the strat; arguably it would be better if these were modeled separately. We've already taken a step in this direction by adding a new requirement type "obstaclesCleared" (and "obstaclesNotCleared") which is a clean, composable way of expressing a requirement that an obstacle is (or is not) cleared without expressing any side effects. 

I would propose that the next step would be to add a new strat property "clearsObstacles" which gives a list of obstacle names which are cleared by doing the strat (similar to "additionalObstacles" now, except "clearsObstacles" would be a property of the strat, not the obstacle); this would be a clean way to express the side effects of the strat without expressing any requirements. I think we could then deprecate and eventually remove the "obstacles" property (along with the "additionalObstacles" contained in it).

**Comment by kjbranch** [comment]
Applied throughout in: 
#948 
#949 
#951 
#955 
#965 
#966 
#970 
#975 
#976
