### ISSUE TITLE
Resource Capacity not passing tests

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#921]
The enum for types used by resourceCapacity does not appear to be read by the validator.  A resourceCapacity object that tries to use "RegularEnergy" or "ReserveEnergy" will through an error.  A resourceCapacity using "Missile", "Super", or "PowerBomb" will pass because those strings are defined elsewhere, most likely in Items.json.

https://discord.com/channels/445948207638511616/534430696635367444/1109037922516209764

**Comment by miketrethewey** [comment]
Related to #942 .
