### ISSUE TITLE
Add Obstacle Validation to Tests

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#922]
- [x] Uniqueness of the ID within the set per room
- [x] Validation of the ID when used by logical objects

**Comment by osse101** [comment]
I think I see  `strats: obstacles: []`

But here's a better list of objects that use obstacles

`strats: obstacles: [ A ]`
`strats: obstacles: additionalObstacles [ A ]`
`strats: clearedObstacles: [A]`
`strats: requires: resetRoom: obstaclesToAvoid [ A ]`
`strats: reqiores: obstaclesCleared: [A]`

Of these obstacles, additionalObstacles, and obstaclesToAvoid are all deprecated.

Then of course `rooms: obstacles` where they are defined.

**Comment by osse101** [comment]
- [ ] `strats: requires: obstaclesNotCleared: [ A ]`

**Comment by miketrethewey** [comment]
Fixed by a27bf63.

**Comment by miketrethewey** [comment]
Related to #942 .
