### ISSUE TITLE
Missing Node Validation

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#923]
- [x] The name field of a Node needs to be unique within the room

- [x] Add validation that Node IDs are defined when used by other schema elements like 
  - [x] `{ "enemies": "homeNode": [ NODE_ID ] }`
  - [x] `{ "links": "from": NODE_ID }`

**Comment by osse101** [comment]
There's some additional validation that can be added to `initiateRemotely`:

- [ ] Ensuring the starting link used by `initiateAt` connecting to the first `destinationNode` exists within the `links' set.

- [ ] Increasing the number of connections allowed by `pathToDoor`.  Making a path of 3 elements was incorrectly failing the test.

**Comment by miketrethewey** [comment]
The path that should be found and valid for 8ebce84 is:
`Maridia/Outer:174:Everest::10:7:3`

The thing should use `search_for_path()` to find it correctly.

**Comment by osse101** [comment]
I want to mention

- [ ] `enemies: betweenNodes: [ID_1, ID_2]`

Some more uses of Node IDs (that I haven't verified if are a problem for tests right now) are

- [ ] `strats: requires: adjacentRunway: fromNode: NODE_ID`
- [ ] `strats: requires: adjacentRunway: inRoomPath: [ID_1, ID_2 ... ID_N]`
- [ ] `strats: requires: adjacenetJumpway: fromNode: NODE_ID`
- [ ] `strats: requires: canComeInCharged: fromNode: NODE_ID`
- [ ] `strats: requires: canComeInCharged: inRoomPath: [ID_1, ID_2, ... ID_N]`
- [ ] `strats: requires: resetRoom: nodes: [ID_1, ID_2, ... ID_N]`
- [ ] `strats: requires: resetRoom: nodesToAvoid: [ID_1, ID_2, ... ID_N]`
- [ ] `strats: requires: comeInWithRMode: [ID_1, ID_2, ... ID_N]`
- [ ] `strats: requires: comeInWithGMode: [ID_1, ID_2, ... ID_N]`
- [ ] `strats: requires: itemNotCollectedAtNode: NODE_ID`

- [ ] `nodes: doorEnvironments: entranceNodes: [NODE_ID]`

Of these all `inRoomPath` and `resetRoom` are on the path to deprecation.

`link: to` and `link: from` look covered.

**Comment by osse101** [comment]
Here is the canLeaveCharged I want to add to "Lower Norfair Spring Ball Maze Room" at Node 3:

```JSON
"canLeaveCharged": [
  {
    "usedTiles": 27,
    "framesRemaining": 0,
    "shinesparkFrames": 35,
    "initiateRemotely": {
      "initiateAt": 4,
      "mustOpenDoorFirst": true,
      "pathToDoor": [
        {
          "destinationNode": 6,
          "strats": ["Quick Kill"]
        },
        {
          "destinationNode": 7,
          "strats": ["Base"]
        },
        {
          "destinationNode": 3,
          "strats": ["Kill While Running"]
        }
      ]
    },
    "strats":[],
    "openEnd": 1
  }
```
And it gives an error when the 4->6, 6->7, and 7->3 strats all exist.
```
Norfair/Lower/East
🟢Norfair/Lower/East:145:Lower Norfair Fireflea Room:5:7:Lower Norfair Fireflea Hjless Walljump::4:6:7
Norfair/Lower/West
Maridia/Inner/Green
Maridia/Inner/Pink
Maridia/Inner/Yellow
Maridia/Outer
🟢Maridia/Outer:173:Fish Tank:7:3:Suitless::10:7:3
Norfair/Upper/Crocomire
Norfair/Upper/East
Norfair/Upper/West
Tourian/Main
Wrecked Ship/Main
🔴ERROR🔴
🔴ERROR: Destination node path not found:Node[Norfair/Lower/East:146:Lower Norfair Spring Ball Maze Room:3]:canLeaveCharged[1]:initiateRemotelyAt[4]:destinationNode[3]
🟡WARNING🟡
🟡WARNING: Link Path:Node[Norfair/Lower/East:146:Lower Norfair Spring Ball Maze Room:3]:canLeaveCharged[1]:initiateRemotelyAt[4]:7 not found!
🟡WARNING: Link Path:Node[Norfair/Lower/East:146:Lower Norfair Spring Ball Maze Room:3]:canLeaveCharged[1]:initiateRemotelyAt[4]:3 not found!
🟡WARNING: Link Path:Node[Maridia/Outer:174:Mt. Everest:3]:canLeaveCharged[1]:initiateRemotelyAt[10]:3 not found!
"::warning title=Warning::Check Log for Details..."
🔴Something fucked up! Bailing!
```

I don't know why the Fireflea Room strat is pointed out because it does not do anything interesting.  
`Walljump::4:6:7` is weird because that room does not have that sequence of links.  Would it be comparing to a node3 in a different room for some reason?

**Comment by osse101** [comment]
Running the above again on the new commit:
```
Norfair/Lower/East
🟢Norfair/Lower/East:145:Lower Norfair Fireflea Room:5:7:Lower Norfair Fireflea Hjless Walljump::4:6:7
🟢Norfair/Lower/East:145:Lower Norfair Fireflea Room:5:7:Lower Norfair Fireflea Hjless Walljump::4:6:7

Norfair/Lower/West
Maridia/Inner/Green
Maridia/Inner/Pink
Maridia/Inner/Yellow

Maridia/Outer
🟢Maridia/Outer:173:Fish Tank:7:3:Suitless::10:7:3
🟢Maridia/Outer:173:Fish Tank:7:3:Suitless::10:7:3

Norfair/Upper/Crocomire
Norfair/Upper/East

Norfair/Upper/West

Tourian/Main
Wrecked Ship/Main

🔴ERROR🔴
🔴ERROR: Destination node path not found:Node[Norfair/Lower/East:146:Lower Norfair Spring Ball Maze Room:3]:canLeaveCharged[1]:initiateRemotelyAt[4]:3
🔴ERROR: Destination node path not found:Node[Norfair/Lower/East:146:Lower Norfair Spring Ball Maze Room:3]:canLeaveCharged[1]:initiateRemotelyAt[4]:destinationNode[3]
🔴Something fucked up! Bailing!
```

**Comment by miketrethewey** [comment]
I haven't been able to grok how to make it successfully find a chain that is 4 or greater.

**Comment by miketrethewey** [comment]
Related to #942 .
Finishing this up and splitting out #945 .
