### ISSUE TITLE
Add reusableRoomwideNotable Validation

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#927]
One really touchy potential problem is the `reusableRoomwideNotable: NAME` value.  

The value used by strats in 
`strats: reusableRoomwideNotable: NAME` 
needs to exactly match an entry in 
`rooms: reusableRoomwideNotable: [{ NAME, note}]`

I do not think it is important to check that the `reusableRoomwideNotable` is used more than once.

And if `strats: reusableRoomwideNotable` exists, then notable for the strat should be true.

**Comment by osse101** [comment]
With #928, reusableRoomwideNotable will require notable to be true as part of the schema, and is part of the tests through that.

**Comment by miketrethewey** [comment]
Related to #942 .
