### ISSUE TITLE
Add leniency to unmorph bomb boost strats with PBs

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#967]

**Comment by blkerby** [comment]
Or maybe this isn't needed after all? 

insomniaspeed video: https://discord.com/channels/1053421401354285129/1079847747307446413/1133215606066384927

**Comment by osse101** [comment]
In that case I just didn't know how to do it.  Its essentially a jumpIntoIBJ with a relatively large window to unmorph.

Most situations that use `canUnmorphBombBoost` have a non-standard jump and bomb placement.  The unmorph timing may change with your vertical speed too.
